---
#
# Copyright 2015 David Rancourt
#
# License info here...
#
#
#
#
#


 - include: section_01.yml
   tags: section1

 - include: section_02.yml
   tags: section2

 - include: section_03.yml
   tags: section3

 - include: section_04.yml
   tags: section4

 - include: section_05.yml
   tags: section5

 - include: section_06.yml
   tags: section6

 - include: section_07.yml
   tags: section7

