---
#
# Copyright 2015 David Rancourt
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#


   - name: 3.1.1 Retain system.log for 90 or more days (Scored)
     copy: >
       src=etc/asl.conf
       dest=/etc/asl.conf
       owner=root
       group=wheel
       mode=0644
     tags:
       - scored
       - section3.1
       - section3.1.1

   - name: 3.1.2 Retain appfirewall.log for 90 or more days (Scored)
     debug: "*** Step performed as part of 3.1.1"
     tags:
       - scored
       - section3.1
       - section3.1.2

   - name: 3.1.3 Retain authd.log for 90 or more days (Scored)
     copy: >           
       src=etc/asl/com.apple.authd
       dest=/etc/asl/com.apple.authd
       owner=root
       group=wheel
       mode=0644
     tags:
       - scored
       - section3.1
       - section3.1.3

   - name: 3.2.1 Enable security auditing (Scored)
     command: sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.auditd.plist
     tags:
       - scored
       - section3.2
       - section3.2.1
