---
#
# Copyright 2015 David Rancourt
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#


   - name: 6.1.1 Display login window as username and password (Scored)
     osx_defaults: domain=com.apple.loginwindow key=SHOWFULLNAME state=present type=bool value=true
     tags:
       - scored
       - section6.1
       - section6.1.1

   - name: 6.1.2 Disable show password hints (Scored)
     osx_defaults: domain=com.apple.loginwindow key=RetriesUntilHint state=present type=int value=0
     tags:
       - scored
       - section6.1 
       - section6.1.2

   - name: 6.1.3 Disable guest account login (Scored)
     osx_defaults: domain=com.apple.loginwindow key=GuestEnabled state=present type=bool value=false
     tags:
       - scored
       - section6.1 
       - section6.1.3

   - name: 6.1.4 Disable allow guest to connect to shared folders (Scored)
     osx_defaults: domain=com.apple.smb.server key=AllowGuestAccess state=present type=bool value=false
     osx_defaults: domain=com.apple.AppleFileServer key=guestAccess state=present type=bool value=false
     tags:
       - scored
       - section6.1 
       - section6.1.4

   - name: 6.2.1 Turn on filename extensions (Scored)
     osx_defaults: domain=NSGlobalDomain key=AppleShowAllExtensions state=present type=bool value=true
     tags:
       - scored
       - section6.2 
       - section6.2.1

   - name: 6.3.1 Disable the automatic run of safe files in Safari (Scored)
     osx_defaults: domain=com.apple.Safari key=AutoOpenSafeDownloads state=present type=bool value=false
     tags:
       - scored
       - section6.3 
       - section6.3.1

   - name: 6.4.1 Use parental controls for systems that are not centrally managed (Not Scored)
     debug: msg"*** Too restrictive"
     tags:
       - scored
       - section6.4 
       - section6.4.1


