---
#
# Copyright 2015 David Rancourt
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

   - name: 3.3.1 Configure Security Auditing Flags (Scored)
     copy: >
       src=etc/security/audit_control
       dest=/etc/security/audit_control
       owner=root
       group=wheel
       mode=0400
     tags:
       - scored
       - section3.3
       - section3.3.1

   - name: 3.4.1 Enable remote logging for Desktops on trusted networks (Not Scored)
     debug: msg="*** Manual intervention suggested"
     tags:
       - scored
       - section3.4
       - section3.4.1

   - name: 3.5.1 Retain install.log for 365 or more days (Scored)
     copy: >
       src=etc/asl/com.apple.install
       dest=/etc/asl/com.apple.install
       owner=root
       group=wheel
       mode=0644
     tags:
       - scored
       - section3.5
       - section3.5.1
